services:
  nest-app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - C:/Users/guiyu/code/mysql-data:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - C:/Users/guiyu/code/redis-data:/data