version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3005:3005'
    networks:
      - common-network
  mysql-container:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - '3306:3306'
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - common-network
networks:
  common-network:
    driver: bridge